# Generated by Django 5.1.2 on 2024-10-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='url_image_profile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
