# Generated by Django 5.1.2 on 2024-11-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_album_favoritealbum_music_albummusic_playlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
