# Generated by Django 5.1.2 on 2024-11-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(default='01JBSX9KFA19GRZ36G23MWE0KC', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='01JBSX9KF6F5XB4R0ZNFDRHY6X', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.CharField(default='01JBSX9KF8CV0D7P82JN5P9F67', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(default='01JBSX9KF9V4K28W6JHV1EBQ3S', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(default='01JBSX9KFBGPHTCZ3QX3RDYZH2', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='id',
            field=models.CharField(default='01JBSX9KF8HRWMPYR9WCSGVYH7', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verify',
            name='id',
            field=models.CharField(default='01JBSX9KFCBAW90SY5GKFVFK3K', max_length=26, primary_key=True, serialize=False),
        ),
    ]
