# Generated by Django 5.1.2 on 2024-11-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_album_background_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(default='01JC3G8KCKJPKZWY1JYK29PM7K', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='01JC3G8KCAXT227CTMJWWV2WN5', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.CharField(default='01JC3G8KCFP4W5ZFYRXFX3NBKF', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(default='01JC3G8KCHNXHC2FFS7RQN43TT', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(default='01JC3G8KCN7B9GMDC54F0MYY52', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='id',
            field=models.CharField(default='01JC3G8KCEFP1HHB10AFHQKK2Z', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verify',
            name='id',
            field=models.CharField(default='01JC3G8KCSTFF5MRTNKKHDT4TY', max_length=26, primary_key=True, serialize=False),
        ),
    ]
