# Generated by Django 5.1.2 on 2024-11-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_album_id_alter_customuser_id_alter_music_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(default='01JC3GD23WCVYXVZ28QBGD1S99', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='01JC3GD23GHXGMP6DSTWSCY111', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.CharField(default='01JC3GD23RVN5VA71J58Q1CXTW', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(default='01JC3GD23TQ300WQC6NW18CYPG', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(default='01JC3GD23YPJKH13E700FXAPR6', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='id',
            field=models.CharField(default='01JC3GD23QWXWEKHQK969KWRNF', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verify',
            name='id',
            field=models.CharField(default='01JC3GD241ZWX8E6JTT8XVVDDB', max_length=26, primary_key=True, serialize=False),
        ),
    ]
