# Generated by Django 5.1.2 on 2024-11-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_album_id_alter_customuser_id_alter_music_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_music',
            field=models.ManyToManyField(through='myapp.PlaylistMusic', to='myapp.music'),
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(default='01JC3GZY6CBJ2Z58T74XJE4Z0X', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='01JC3GZY67EZNDAPB40X4CF7T8', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.CharField(default='01JC3GZY6AZFW5NFDNMVJN1XVV', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(default='01JC3GZY6BC51WRE9NV20DZ07K', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlistmusic',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlistmusic_set', to='myapp.music'),
        ),
        migrations.AlterField(
            model_name='playlistmusic',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlistmusic_set', to='myapp.playlist'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(default='01JC3GZY6CQZVAC3W0PRAYXCD0', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='id',
            field=models.CharField(default='01JC3GZY690HXVFC2ZBJAMTK6W', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verify',
            name='id',
            field=models.CharField(default='01JC3GZY6F6JM53XZC4Q50MSGE', max_length=26, primary_key=True, serialize=False),
        ),
    ]
