# Generated by Django 5.1.2 on 2024-11-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_playlist_playlist_music_alter_album_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_music',
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(default='01JC3H1C2QM64XGCAS2XQNSXQ4', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='01JC3H1C2G08J5F6NBH53PVA2M', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.CharField(default='01JC3H1C2MSVKBYVHNZSAC2F8R', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(default='01JC3H1C2PDGRX7JE239ZJYGQF', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlistmusic',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.music'),
        ),
        migrations.AlterField(
            model_name='playlistmusic',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.playlist'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(default='01JC3H1C2S35Z1P0RRPAZSNHZT', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='id',
            field=models.CharField(default='01JC3H1C2KFJW8PKF8NBV80XAA', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verify',
            name='id',
            field=models.CharField(default='01JC3H1C2W7HZM29YF3EJH7846', max_length=26, primary_key=True, serialize=False),
        ),
    ]
