# Generated by Django 5.1.2 on 2024-11-07 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_playlist_playlist_music_alter_album_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(default='01JC3HEFC0AFZDJC1D0XCKJCAK', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='01JC3HEFBRRSJADNRCB274GTKX', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.CharField(default='01JC3HEFBXCVR16KKWTGBWD9YJ', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(default='01JC3HEFBZBBE9QMKBG7RKVD82', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlistmusic',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_music', to='myapp.music'),
        ),
        migrations.AlterField(
            model_name='playlistmusic',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_music', to='myapp.playlist'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(default='01JC3HEFC2W7DC1A25TQGHTW2A', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='id',
            field=models.CharField(default='01JC3HEFBW3KQDMH8P44HCWR0B', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verify',
            name='id',
            field=models.CharField(default='01JC3HEFC63DA8YQCGKYW15NZM', max_length=26, primary_key=True, serialize=False),
        ),
    ]
