# Generated by Django 5.1.2 on 2024-11-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_album_id_alter_customuser_id_alter_music_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(default='01JC6JJ9H44YSP18QA9TH99ADB', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='01JC6JJ9GVVVS172PT5XHY5BX9', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.CharField(default='01JC6JJ9H05PZKXSR9TNR4TNR7', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(default='01JC6JJ9H2K15C0MPSN0TNZTW8', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(default='01JC6JJ9H61BSE9VQ6GQ5P3D9T', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='id',
            field=models.CharField(max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verify',
            name='id',
            field=models.CharField(default='01JC6JJ9H9VG8WR1K18CZ9483C', max_length=26, primary_key=True, serialize=False),
        ),
    ]
