# Generated by Django 5.1.2 on 2024-11-08 19:31

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_album_id_alter_customuser_id_alter_music_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(default='01JC6M4W5XMSW6WXCNP3R6GKPH', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=myapp.models.generate_ulid, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.CharField(default='01JC6M4W5S3V01GF8RK92AY8JE', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(default='01JC6M4W5VZYCYAGJNEMNH1J60', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(default='01JC6M4W5Y3RG43FG4MFZT6SWY', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='id',
            field=models.CharField(default='01JC6M4W5R096Y9Z6TYWCXB0V1', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verify',
            name='id',
            field=models.CharField(default='01JC6M4W61ADW9FNWGWSFDPVAT', max_length=26, primary_key=True, serialize=False),
        ),
    ]
