# Generated by Django 5.1.2 on 2024-11-20 18:34

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_album_id_alter_customuser_id_alter_music_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(default=myapp.models.generate_ulid, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='albummusic',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_album', to='myapp.album'),
        ),
        migrations.AlterField(
            model_name='albummusic',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_album', to='myapp.music'),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.CharField(default=myapp.models.generate_ulid, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(default=myapp.models.generate_ulid, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(default='01JD5DMN4GXVYXAFXS5JSSPRAE', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='id',
            field=models.CharField(default='01JD5DMN4AYGQMYY72EZRZ25AC', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verify',
            name='id',
            field=models.CharField(default='01JD5DMN4KT7SBZ6Q4JJ1TFME4', max_length=26, primary_key=True, serialize=False),
        ),
    ]
