# Generated by Django 5.1.2 on 2024-11-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_album_id_alter_albummusic_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='is_subtitle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(default='01JDM45SWTNADC6JW2E8AXH4W7', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='id',
            field=models.CharField(default='01JDM45SWQAEKYG6VMJ4VY5Z9V', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verify',
            name='id',
            field=models.CharField(default='01JDM45SWVDR4WQMQ5BQ73CVMZ', max_length=26, primary_key=True, serialize=False),
        ),
    ]
