# Generated by Django 5.1.2 on 2024-12-02 13:25

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_music_is_subtitle_alter_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(default=myapp.models.generate_ulid, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='id',
            field=models.CharField(default='01JE3RRNSF78WHVG2KQAER6XTZ', max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verify',
            name='id',
            field=models.CharField(default=myapp.models.generate_ulid, max_length=26, primary_key=True, serialize=False),
        ),
    ]
